# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DCVDocMobile ] && rm -rf DCVDocMobile
          [ -d capture-vision-docs-mobile ] && rm -rf capture-vision-docs-mobile
          [ -d Docs-Template-Repo-Preview-DCV2 ] && rm -rf Docs-Template-Repo-Preview-DCV2
          [ ! -d DCVDocMobile ] && mkdir -p DCVDocMobile

          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/capture-vision-docs-mobile.git capture-vision-docs-mobile
          git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cp -rfp ./capture-vision-docs-mobile/* ./DCVDocMobile/
          cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCVDocMobile/
          cd DCVDocMobile && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DCVDocMobile/_site/
          server-dir: /www.dynamsoft.com/capture-vision/docs/mobile/

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DCVDocMobilePreview ] && rm -rf DCVDocMobilePreview
          [ -d capture-vision-docs-mobile-preview ] && rm -rf capture-vision-docs-mobile-preview
          [ -d Docs-Template-Repo-Preview-DCV2 ] && rm -rf Docs-Template-Repo-Preview-DCV2
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DCVDocMobilePreview ] && mkdir -p DCVDocMobilePreview
          git clone --depth 1 --branch preview https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PAT }}@github.com/dynamsoft-docs/capture-vision-docs-mobile.git capture-vision-docs-mobile-preview
          git clone --depth 1 --branch jenny-preview-branch https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cp -rfp ./capture-vision-docs-mobile-preview/* ./DCVDocMobilePreview/
          cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DCVDocMobilePreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCVDocMobilePreview/_config.yml
          cd DCVDocMobilePreview && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DCVDocMobilePreview/_site/
          server-dir: /www.dynamsoft.com/capture-vision/docs/mobile/
# old
      # - name: clear space
      #   run: |
      #     cd /home/ubuntu 
      #     [ -d DCVDocPreview ] && rm -rf DCVDocPreview
      #     [ -d capture-vision-docs-mobile-preview ] && rm -rf capture-vision-docs-mobile-preview
      #     [ -d Docs-Template-Repo-preview ] && rm -rf Docs-Template-Repo-preview
      #     cd /home/ubuntu

      # - name: Build the site
      #   run: |
      #     cd /home/ubuntu
      #     [ ! -d DCVDocPreview ] && mkdir -p DCVDocPreview
      #     [ ! -d capture-vision-docs-mobile-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/capture-vision-docs-mobile.git capture-vision-docs-mobile-preview          
      #     [ ! -d Docs-Template-Repo-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-preview
      #     cd capture-vision-docs-mobile-preview && git pull && cd .. && cp -rfp ./capture-vision-docs-mobile-preview/* ./DCVDocPreview/
      #     cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DCVDocPreview/
      #     sed -i -e "1,3s/blob\/master$/blob\/preview/" \
      #     -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DCVDocPreview/_config.yml
      #     cd DCVDocPreview && bundle exec jekyll build

      # - name: Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: ${{ secrets.FTP_TEST_SITE_SERVER }}
      #     username: ${{ secrets.FTP_TEST_SITE_USER }}
      #     password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
      #     port: 7500 
      #     local-dir: /home/ubuntu/DCVDocPreview/_site/
      #     server-dir: /www.dynamsoft.com/capture-vision/docs/          
          
